from __future__ import annotations
from abc import ABC, abstractmethod
from pathlib import Path

class GitProvider(ABC):
    @abstractmethod
    def create_branch(self, name: str, from_ref: str = "HEAD") -> str: ...

    @abstractmethod
    def commit(self, message: str, add_all: bool = True) -> str:
        """Stage all changes (if add_all) and create a commit. Returns the new SHA."""
        ...

    @abstractmethod
    def checkout(self, branch_name: str) -> None: ...
    @abstractmethod
    def stash(self, message: str) -> str: ...
    @abstractmethod
    def stash_pop(self, ref: str) -> None: ...
    @abstractmethod
    def reset_hard(self, ref: str) -> None: ...
    @abstractmethod
    def get_last_green_commit(self) -> str: ...
    @abstractmethod
    def record_green_commit(self, sha: str) -> None: ...
    @abstractmethod
    def current_branch(self) -> str: ...
    @abstractmethod
    def uncommitted_files(self) -> list[str]: ...

    # ── Speculative branch isolation ──────────────────────────────────────

    @abstractmethod
    def create_worktree(self, branch_name: str, worktree_path: Path) -> Path: ...

    @abstractmethod
    def remove_worktree(self, worktree_path: Path) -> None: ...
